syntax = "proto3";

option csharp_namespace = "nShop.Catalog.Api";

package catalog;

service CatalogService {
  rpc CreateCategory (GrpcCreateCategoryRequest) returns (GrpcCreateCategoryResponse);
  rpc UpdateCategory (GrpcUpdateCategoryRequest) returns (GrpcUpdateCategoryResponse);
  rpc FindCategories (GrpcFindCategoriesRequest) returns (GrpcFindCategoriesResponse);
  rpc FindCategoryById (GrpcFindCategoryByIdRequest) returns (GrpcFindCategoryByIdResponse);
  rpc PublishCategory (GrpcPublishCategoryRequest) returns (GrpcPublishCategoryResponse);
  rpc UnpublishCategory (GrpcUnpublishCategoryRequest) returns (GrpcUnpublishCategoryResponse);

  rpc CreateProduct (GrpcCreateProductRequest) returns (GrpcCreateProductResponse);
  rpc UpdateProduct (GrpcUpdateProductRequest) returns (GrpcUpdateProductResponse);
  rpc FindProducts (GrpcFindProductsRequest) returns (GrpcFindProductsResponse);
  rpc FindProductById (GrpcFindProductByIdRequest) returns (GrpcFindProductByIdResponse);
  rpc UpdateProductGroups (GrpcUpdateProductGroupsRequest) returns (GrpcUpdateProductGroupsResponse);
  rpc PublishProduct (GrpcPublishProductRequest) returns (GrpcPublishProductResponse);
  rpc UnpublishProduct (GrpcUnpublishProductRequest) returns (GrpcUnpublishProductResponse);

  rpc AddVariationDimensions (GrpcAddVariationDimensionsRequest) returns (GrpcAddVariationDimensionsResponse);

  rpc AddVariant(GrpcAddVariantRequest) returns (GrpcAddVariantResponse);
  rpc UpdateVariantPrice(GrpcUpdateVariantPriceRequest) returns (GrpcUpdateVariantPriceResponse);
  rpc UpdateVariant(GrpcUpdateVariantRequest) returns (GrpcUpdateVariantResponse);

  rpc FulltextSearch(GrpcFulltextSearchRequest) returns (GrpcFulltextSearchResponse);
}

message GrpcPaging {
  int64 offset = 1;
  int64 limit = 2;
}

message GrpcResponsePagination {
  int64 offset = 1;
  int64 page_length = 2;
  int64 total = 3;
}

message GrpcCreateCategoryRequest {
  string tenant_id = 1;
  string parent_id = 2;
  string name = 3;
  string slug = 4;
}

message GrpcCreateCategoryResponse {
  string category_id = 1;
}

message GrpcUpdateCategoryRequest {
  string category_id = 1;
  string parent_id = 2;
  string name = 3;
  string slug = 4;
}

message GrpcUpdateCategoryResponse {
}

message GrpcPublishCategoryRequest {
  string category_id = 1;
}

message GrpcPublishCategoryResponse {
}

message GrpcUnpublishCategoryRequest {
  string category_id = 1;
}

message GrpcUnpublishCategoryResponse {
}

message GrpcCategory {
  string id = 1;
  string tenant_id = 2;
  string parent_id = 3;
  string name = 4;
  string slug = 5;
}

message GrpcVariationDimension {
  string name = 1;
  string display_name = 2;
  string display_position = 3;
  GrpcVariationDimensionDisplayStyles display_style = 4;
  repeated string values = 5;
}

message GrpcProduct {
  string id = 1;
  string category_id = 2;
  string name = 3;
  string description = 4;
  repeated string tags = 5;
  string slug = 6;
  repeated string images = 7;
  repeated string groups = 8;
  string tenant_id = 9;
  repeated GrpcVariationDimension variation_dimensions = 10;
  repeated GrpcVariant variants = 11;
}

message GrpcDimensionValue {
  string name = 1;
  string value = 2;
}

message GrpcVariant {
  string id = 1;
  string product_id = 2;
  string name = 3;
  string sku = 4;
  bool is_default = 5;
  double price = 6;
  double discount_price = 7;
  repeated GrpcDimensionValue dimension_values = 8;
}

message GrpcFindCategoriesRequest {
  repeated string ids = 1;
  string tenant_id = 2;
  string parent_id = 3;
  GrpcPaging paging = 4;
}

message GrpcFindCategoriesResponse {
  repeated GrpcCategory categories = 1;
}

message GrpcFindCategoryByIdRequest {
  string category_id = 1;
}

message GrpcFindCategoryByIdResponse {
  optional GrpcCategory category = 1;
  GrpcResponsePagination pagination = 2;
}

message GrpcCreateProductRequest {
  string tenant_id = 1;
  string category_id = 2;
  string name = 3;
  string description = 4;
  double price = 5;
  repeated string tags = 6;
  string slug = 7;
  repeated string images = 8;
  repeated string groups = 9;
}

message GrpcCreateProductResponse {
  string product_id = 1;
}

message GrpcUpdateProductRequest {
  string product_id = 1;
  string category_id = 2;
  string name = 3;
  string description = 4;
  repeated string tags = 6;
  string slug = 7;
  repeated string images = 8;
  repeated string groups = 9;
}

message GrpcUpdateProductResponse {
}

message GrpcUpdateVariantPriceRequest {
  string product_id = 1;
  string variant_id = 2;
  double price = 3;
  double discount_price = 4;
}

message GrpcUpdateVariantPriceResponse {
}

enum GrpcVariationDimensionDisplayStyles {
  TEXT = 0;
  COLOR = 1;
}

message GrpcFindProductsRequest {
  message Filters {
    repeated string ids = 1;
    string name = 2;
    double price_from = 3;
    double price_to = 4;
    string category_id = 5;
    string slug = 6;
    repeated string tags = 7;
    repeated string groups = 8;
  }
  string tenant_id = 1;
  Filters filters = 2;
  GrpcPaging paging = 3;
}

message GrpcFindProductsResponse {
  repeated GrpcProduct products = 1;
  GrpcResponsePagination pagination = 2;
}

message GrpcFindProductByIdRequest {
  string product_id = 1;
}

message GrpcFindProductByIdResponse {
  optional GrpcProduct product = 1;
}

message GrpcUpdateProductGroupsRequest {
  string product_id = 1;
  repeated string groups = 2;
}

message GrpcUpdateProductGroupsResponse {
}

message GrpcPublishProductRequest {
  string product_id = 1;
}

message GrpcPublishProductResponse {
}

message GrpcUnpublishProductRequest {
  string product_id = 1;
}

message GrpcUnpublishProductResponse {
}

message GrpcAddVariationDimensionsRequest {
  string product_id = 1;
  repeated GrpcVariationDimension dimensions = 2;
}

message GrpcAddVariationDimensionsResponse {
}

message GrpcAddVariantRequest {
  string product_id = 1;
  string name = 2;
  string sku = 3;
  double price = 4;
  double discount_price = 5;
  repeated GrpcDimensionValue dimension_values = 6;
}

message GrpcAddVariantResponse {
  string variant_id = 1;
}

message GrpcUpdateVariantRequest {
  string product_id = 1;
  string variant_id = 2;
  string name = 3;
  string sku = 4;
}

message GrpcUpdateVariantResponse {
}

message GrpcFulltextSearchRequest {
  message Filters {
    double price_from = 1;
    double price_to = 2;
  }

  string tenant_id = 1;
  string query = 2;
  Filters filters = 3;
  GrpcPaging paging = 4;
}

message GrpcFulltextSearchResponse {
  message GrpcFulltextSearchProduct {
    string product_id = 1;
    string name = 2;
  }
  repeated GrpcFulltextSearchProduct products = 1;
  GrpcResponsePagination pagination = 2;
}
