<Project Sdk="Aspire.AppHost.Sdk/13.3.0">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <UserSecretsId>dad787b3-6bce-481b-99dc-3303d2262db0</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Aspire.Hosting.Kafka" Version="13.3.0" />
      <PackageReference Include="Aspire.Hosting.MongoDB" Version="13.3.0" />
      <PackageReference Include="Aspire.Hosting.PostgreSQL" Version="13.3.0" />
      <PackageReference Include="Aspire.Hosting.Redis" Version="13.3.0" />
      <PackageReference Include="Confluent.Kafka" Version="2.15.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Apis\Catalog\nShop.Catalog.Api\nShop.Catalog.Api.csproj" />
      <ProjectReference Include="..\Aspire\nShop.Aspire.EventStoreDB\nShop.Aspire.EventStoreDB.csproj" IsAspireProjectResource="false" />
    </ItemGroup>

</Project>
